version: '3'
services:

  # PHP
  ssl_monitor_php_service:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: ssl_monitor_php_container
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: ssl_monitor_php_service
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - ssl-monitor-network

  # Nginx
  ssl_monitor_nginx_service:
    image: nginx:alpine
    container_name: ssl_monitor_nginx_container
    restart: unless-stopped
    tty: true
    ports:
      - "${NGINX_LOCAL_PORT}:80"
      # - "443:443" SSL Пока что нет
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - ssl-monitor-network

  # MySQL
  ssl_monitor_mysql_service:
    image: mysql:5.7.22
    container_name: ssl_monitor_mysql_container
    restart: unless-stopped
    tty: true
    ports:
      - "${MYSQL_LOCAL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ssl_monitor
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: ssl_monitor_mysql_service
    volumes:
      - ssl_monitor_mysql_data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - ssl-monitor-network

networks:
  ssl-monitor-network:
    driver: bridge
volumes:
  ssl_monitor_mysql_data:
    driver: local